name: fed-id-demo-workflow
on: [workflow_dispatch]
jobs:
  scan-config:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ${{ github.workspace }}/terraform
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List files in working directory
        run: ls

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          hide-progress: true
          output: trivy.txt
          tf-vars: ${{ github.workspace }}/terraform/environments/dev.tfvars

      - name: List files in working directory
        run: ls
      - name: Cat trivy.txt
        run: cat trivy.txt

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
