name: fed-id-demo-workflow
on: [workflow_dispatch]
jobs:
  scan-config:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ${{ github.workspace }}/terraform
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          hide-progress: true
          output: trivy.txt
          tf-vars: ${{ github.workspace }}/terraform/environments/dev.tfvars

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
  tf-plan:
    runs-on: ubuntu-latest
    needs: scan-config
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -var-file=environments/dev.tfvars -out=tfplan

      - name: Publish Plan to Summary
        run: |
          {
            echo "### Terraform Plan"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```terraform'
            cat tfplan
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
